# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftMemoryManagement' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftMemoryManagement
  pod 'RxSwift', '~> 4.2.0'
  pod 'RxDataSources', '~> 3.0.2'

  target 'RxSwiftMemoryManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftMemoryManagementUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
