# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UITableView+UIKeyboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UITableView+UIKeyboard
  pod 'RxDataSources'
  pod 'RxKeyboard'
  pod 'IQKeyboardManagerSwift'

  target 'UITableView+UIKeyboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITableView+UIKeyboardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
