# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleOptionsList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleOptionsList
  pod 'RxDataSources', '~> 3.0.2'

  target 'SimpleOptionsListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleOptionsListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
